import Head from 'next/head';
import Image from 'next/image';
export default function Home() {
  return (
    <div className="container w-10/12 mx-auto mt-20 md:mt-40 lg:w-9/12 xl:7/12">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex flex-col md:flex-row ">
          <div
            className="brightOrange rounded-t-xl py-8 px-7 
          md:rounded-l-xl md:rounded-t-none
          md:px-10
         "
          >
            <Image
              src="/images/icon-sedans.svg"
              alt="sedan icon"
              width={64}
              height={40}
            ></Image>
            <h2 className="mt-6 text-white font-semibold text-4xl uppercase tracking-tight">
              Sedans
            </h2>
            <p className="mt-6 text-white text-opacity-75 md:min-h-44 lg:min-h-36 xl:min-h-20">
              Choose a sedan for its affordability and excellent fuel economy.
              Ideal for cruising in the city or on your next road trip.
            </p>
            <button className="hover:bg-yellow-200 focus:outline-none focus:ring-2 focus:ring-white mt-6 bg-gray-100 font-semibold px-7 py-3 rounded-3xl brightOrange-font">
              Learn More
            </button>
          </div>
          <div className="darkCyan py-8 px-7 md:px-10">
            <Image
              src="/images/icon-suvs.svg"
              alt="sedan icon"
              width={64}
              height={40}
            ></Image>
            <h2 className="mt-6 text-white font-semibold text-4xl uppercase tracking-tight">
              SUVs
            </h2>
            <p className="mt-6 text-white text-opacity-75 md:min-h-44 lg:min-h-36 xl:min-h-20">
              Take an SUV for its spacious interior, power, and versatility.
              Perfect for your next family vacation and off-road adventures.
            </p>
            <button className="hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-white mt-6 bg-gray-100 font-semibold px-7 py-3 rounded-3xl darkCyan-font">
              Learn More
            </button>
          </div>
          <div className="veryDarkCyan rounded-b-xl py-8 px-7 md:rounded-r-xl md:rounded-b-none md:px-10 ">
            <Image
              src="/images/icon-luxury.svg"
              alt="sedan icon"
              width={64}
              height={40}
            ></Image>
            <h2 className="mt-6 text-gray-100 font-semibold text-4xl uppercase tracking-tight">
              Luxury
            </h2>
            <p className="mt-6 text-white text-opacity-75 md:min-h-44 lg:min-h-36 xl:min-h-20">
              Luxury Cruise in the best car brands without the bloated prices.
              Enjoy the enhanced comfort of a luxury rental and arrive in style.
            </p>
            <button className="hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-white mt-6 bg-gray-100 font-semibold px-7 py-3 rounded-3xl veryDarkCyan-font">
              Learn More
            </button>
          </div>
        </div>
      </main>

      <footer className="text-center mt-5">
        Coded by
        <a
          href="https://github.com/HangCcZ"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-400"
        >
          {' '}
          Hang Chen{'. '}
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
